
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v3.2.10)

2026-09-06T01:20:14.625+08:00  INFO 32892 --- [ai-knowledge-base] [           main] com.kb.demo.AiKnowledgeBaseApplication   : Starting AiKnowledgeBaseApplication v0.0.1-SNAPSHOT using Java 25.0.2 with PID 32892 (D:\Project\enterprise-agent\target\ai-knowledge-base-0.0.1-SNAPSHOT.jar started by Administrator in D:\Project\enterprise-agent)
2026-09-06T01:20:14.628+08:00 DEBUG 32892 --- [ai-knowledge-base] [           main] com.kb.demo.AiKnowledgeBaseApplication   : Running with Spring Boot v3.2.10, Spring v6.1.13
2026-09-06T01:20:14.629+08:00  INFO 32892 --- [ai-knowledge-base] [           main] com.kb.demo.AiKnowledgeBaseApplication   : No active profile set, falling back to 1 default profile: "default"
2026-09-06T01:20:17.479+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2026-09-06T01:20:17.484+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Elasticsearch repositories in DEFAULT mode.
2026-09-06T01:20:17.575+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.AnswerEvaluationRepository; If you want this repository to be a Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ElasticsearchRepository, org.springframework.data.elasticsearch.repository.ElasticsearchRepository
2026-09-06T01:20:17.579+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DepartmentRepository; If you want this repository to be a Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ElasticsearchRepository, org.springframework.data.elasticsearch.repository.ElasticsearchRepository
2026-09-06T01:20:17.582+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentCategoryRelationRepository; If you want this repository to be a Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ElasticsearchRepository, org.springframework.data.elasticsearch.repository.ElasticsearchRepository
2026-09-06T01:20:17.584+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentCategoryRepository; If you want this repository to be a Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ElasticsearchRepository, org.springframework.data.elasticsearch.repository.ElasticsearchRepository
2026-09-06T01:20:17.586+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentChunkRepository; If you want this repository to be a Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ElasticsearchRepository, org.springframework.data.elasticsearch.repository.ElasticsearchRepository
2026-09-06T01:20:17.588+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentIndexSyncTaskRepository; If you want this repository to be a Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ElasticsearchRepository, org.springframework.data.elasticsearch.repository.ElasticsearchRepository
2026-09-06T01:20:17.594+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentRepository; If you want this repository to be a Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ElasticsearchRepository, org.springframework.data.elasticsearch.repository.ElasticsearchRepository
2026-09-06T01:20:17.597+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentTagRelationRepository; If you want this repository to be a Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ElasticsearchRepository, org.springframework.data.elasticsearch.repository.ElasticsearchRepository
2026-09-06T01:20:17.598+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentTagRepository; If you want this repository to be a Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ElasticsearchRepository, org.springframework.data.elasticsearch.repository.ElasticsearchRepository
2026-09-06T01:20:17.600+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentVersionRepository; If you want this repository to be a Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ElasticsearchRepository, org.springframework.data.elasticsearch.repository.ElasticsearchRepository
2026-09-06T01:20:17.602+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.PermissionRepository; If you want this repository to be a Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ElasticsearchRepository, org.springframework.data.elasticsearch.repository.ElasticsearchRepository
2026-09-06T01:20:17.604+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.RoleRepository; If you want this repository to be a Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ElasticsearchRepository, org.springframework.data.elasticsearch.repository.ElasticsearchRepository
2026-09-06T01:20:17.607+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.UploadProgressRepository; If you want this repository to be a Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ElasticsearchRepository, org.springframework.data.elasticsearch.repository.ElasticsearchRepository
2026-09-06T01:20:17.610+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.UserRepository; If you want this repository to be a Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ElasticsearchRepository, org.springframework.data.elasticsearch.repository.ElasticsearchRepository
2026-09-06T01:20:17.611+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 117 ms. Found 0 Elasticsearch repository interfaces.
2026-09-06T01:20:17.621+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2026-09-06T01:20:17.622+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Reactive Elasticsearch repositories in DEFAULT mode.
2026-09-06T01:20:17.632+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Reactive Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.AnswerEvaluationRepository; If you want this repository to be a Reactive Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ReactiveElasticsearchRepository
2026-09-06T01:20:17.632+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Reactive Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DepartmentRepository; If you want this repository to be a Reactive Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ReactiveElasticsearchRepository
2026-09-06T01:20:17.632+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Reactive Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentCategoryRelationRepository; If you want this repository to be a Reactive Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ReactiveElasticsearchRepository
2026-09-06T01:20:17.633+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Reactive Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentCategoryRepository; If you want this repository to be a Reactive Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ReactiveElasticsearchRepository
2026-09-06T01:20:17.633+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Reactive Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentChunkRepository; If you want this repository to be a Reactive Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ReactiveElasticsearchRepository
2026-09-06T01:20:17.633+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Reactive Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentIndexSyncTaskRepository; If you want this repository to be a Reactive Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ReactiveElasticsearchRepository
2026-09-06T01:20:17.634+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Reactive Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentRepository; If you want this repository to be a Reactive Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ReactiveElasticsearchRepository
2026-09-06T01:20:17.634+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Reactive Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentTagRelationRepository; If you want this repository to be a Reactive Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ReactiveElasticsearchRepository
2026-09-06T01:20:17.634+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Reactive Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentTagRepository; If you want this repository to be a Reactive Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ReactiveElasticsearchRepository
2026-09-06T01:20:17.635+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Reactive Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentVersionRepository; If you want this repository to be a Reactive Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ReactiveElasticsearchRepository
2026-09-06T01:20:17.635+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Reactive Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.PermissionRepository; If you want this repository to be a Reactive Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ReactiveElasticsearchRepository
2026-09-06T01:20:17.635+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Reactive Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.RoleRepository; If you want this repository to be a Reactive Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ReactiveElasticsearchRepository
2026-09-06T01:20:17.635+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Reactive Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.UploadProgressRepository; If you want this repository to be a Reactive Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ReactiveElasticsearchRepository
2026-09-06T01:20:17.636+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Reactive Elasticsearch - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.UserRepository; If you want this repository to be a Reactive Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ReactiveElasticsearchRepository
2026-09-06T01:20:17.636+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 14 ms. Found 0 Reactive Elasticsearch repository interfaces.
2026-09-06T01:20:17.653+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2026-09-06T01:20:17.655+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2026-09-06T01:20:17.997+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 333 ms. Found 14 JPA repository interfaces.
2026-09-06T01:20:18.033+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2026-09-06T01:20:18.035+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2026-09-06T01:20:18.055+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Redis - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.AnswerEvaluationRepository; If you want this repository to be a Redis repository, consider annotating your entities with one of these annotations: org.springframework.data.redis.core.RedisHash (preferred), or consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository
2026-09-06T01:20:18.055+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Redis - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DepartmentRepository; If you want this repository to be a Redis repository, consider annotating your entities with one of these annotations: org.springframework.data.redis.core.RedisHash (preferred), or consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository
2026-09-06T01:20:18.055+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Redis - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentCategoryRelationRepository; If you want this repository to be a Redis repository, consider annotating your entities with one of these annotations: org.springframework.data.redis.core.RedisHash (preferred), or consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository
2026-09-06T01:20:18.056+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Redis - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentCategoryRepository; If you want this repository to be a Redis repository, consider annotating your entities with one of these annotations: org.springframework.data.redis.core.RedisHash (preferred), or consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository
2026-09-06T01:20:18.056+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Redis - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentChunkRepository; If you want this repository to be a Redis repository, consider annotating your entities with one of these annotations: org.springframework.data.redis.core.RedisHash (preferred), or consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository
2026-09-06T01:20:18.056+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Redis - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentIndexSyncTaskRepository; If you want this repository to be a Redis repository, consider annotating your entities with one of these annotations: org.springframework.data.redis.core.RedisHash (preferred), or consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository
2026-09-06T01:20:18.056+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Redis - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentRepository; If you want this repository to be a Redis repository, consider annotating your entities with one of these annotations: org.springframework.data.redis.core.RedisHash (preferred), or consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository
2026-09-06T01:20:18.057+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Redis - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentTagRelationRepository; If you want this repository to be a Redis repository, consider annotating your entities with one of these annotations: org.springframework.data.redis.core.RedisHash (preferred), or consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository
2026-09-06T01:20:18.057+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Redis - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentTagRepository; If you want this repository to be a Redis repository, consider annotating your entities with one of these annotations: org.springframework.data.redis.core.RedisHash (preferred), or consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository
2026-09-06T01:20:18.058+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Redis - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.DocumentVersionRepository; If you want this repository to be a Redis repository, consider annotating your entities with one of these annotations: org.springframework.data.redis.core.RedisHash (preferred), or consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository
2026-09-06T01:20:18.058+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Redis - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.PermissionRepository; If you want this repository to be a Redis repository, consider annotating your entities with one of these annotations: org.springframework.data.redis.core.RedisHash (preferred), or consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository
2026-09-06T01:20:18.059+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Redis - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.RoleRepository; If you want this repository to be a Redis repository, consider annotating your entities with one of these annotations: org.springframework.data.redis.core.RedisHash (preferred), or consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository
2026-09-06T01:20:18.060+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Redis - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.UploadProgressRepository; If you want this repository to be a Redis repository, consider annotating your entities with one of these annotations: org.springframework.data.redis.core.RedisHash (preferred), or consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository
2026-09-06T01:20:18.060+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .RepositoryConfigurationExtensionSupport : Spring Data Redis - Could not safely identify store assignment for repository candidate interface com.kb.demo.repository.UserRepository; If you want this repository to be a Redis repository, consider annotating your entities with one of these annotations: org.springframework.data.redis.core.RedisHash (preferred), or consider extending one of the following types with your repository: org.springframework.data.keyvalue.repository.KeyValueRepository
2026-09-06T01:20:18.060+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 11 ms. Found 0 Redis repository interfaces.
2026-09-06T01:20:20.976+08:00  INFO 32892 --- [ai-knowledge-base] [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
2026-09-06T01:20:21.008+08:00  INFO 32892 --- [ai-knowledge-base] [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2026-09-06T01:20:21.009+08:00  INFO 32892 --- [ai-knowledge-base] [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.30]
2026-09-06T01:20:21.083+08:00  INFO 32892 --- [ai-knowledge-base] [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2026-09-06T01:20:21.084+08:00  INFO 32892 --- [ai-knowledge-base] [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 6374 ms
2026-09-06T01:20:21.958+08:00  INFO 32892 --- [ai-knowledge-base] [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2026-09-06T01:20:22.103+08:00  INFO 32892 --- [ai-knowledge-base] [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.4.10.Final
2026-09-06T01:20:22.202+08:00  INFO 32892 --- [ai-knowledge-base] [           main] o.h.c.internal.RegionFactoryInitiator    : HHH000026: Second-level cache disabled
2026-09-06T01:20:22.607+08:00  INFO 32892 --- [ai-knowledge-base] [           main] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
2026-09-06T01:20:22.664+08:00  INFO 32892 --- [ai-knowledge-base] [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2026-09-06T01:20:23.100+08:00  INFO 32892 --- [ai-knowledge-base] [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@5f2ad3d5
2026-09-06T01:20:23.103+08:00  INFO 32892 --- [ai-knowledge-base] [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2026-09-06T01:20:25.929+08:00  INFO 32892 --- [ai-knowledge-base] [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000489: No JTA platform available (set 'hibernate.transaction.jta.platform' to enable JTA platform integration)
Hibernate: 
    alter table document_chunks 
       add column document_version integer not null
Hibernate: 
    alter table document_index_sync_tasks 
       add column target_version integer
Hibernate: 
    alter table documents 
       add column active_version integer not null
Hibernate: 
    alter table upload_progress 
       add column attempt_token varchar(36)
Hibernate: 
    alter table upload_progress 
       add column generation integer not null
Hibernate: 
    alter table upload_progress 
       add column last_error varchar(500)
2026-09-06T01:20:26.903+08:00  INFO 32892 --- [ai-knowledge-base] [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2026-09-06T01:20:27.765+08:00 DEBUG 32892 --- [ai-knowledge-base] [           main] c.k.d.security.JwtAuthenticationFilter   : Filter 'jwtAuthenticationFilter' configured for use
2026-09-06T01:20:27.768+08:00 DEBUG 32892 --- [ai-knowledge-base] [           main] o.s.w.f.ServerHttpObservationFilter      : Filter 'webMvcObservationFilter' configured for use
2026-09-06T01:20:27.916+08:00  INFO 32892 --- [ai-knowledge-base] [           main] o.s.d.j.r.query.QueryEnhancerFactory     : Hibernate is in classpath; If applicable, HQL parser will be used.
2026-09-06T01:20:32.217+08:00  INFO 32892 --- [ai-knowledge-base] [           main] ai.djl.util.Platform                     : Found matching platform from: jar:nested:/D:/Project/enterprise-agent/target/ai-knowledge-base-0.0.1-SNAPSHOT.jar/!BOOT-INF/lib/tokenizers-0.28.0.jar!/native/lib/tokenizers.properties
2026-09-06T01:20:32.317+08:00  WARN 32892 --- [ai-knowledge-base] [           main] a.d.h.tokenizers.HuggingFaceTokenizer    : maxLength is not explicitly specified, use modelMaxLength: 512
2026-09-06T01:20:35.162+08:00  WARN 32892 --- [ai-knowledge-base] [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'documentIngestionController' defined in URL [jar:nested:/D:/Project/enterprise-agent/target/ai-knowledge-base-0.0.1-SNAPSHOT.jar/!BOOT-INF/classes/!/com/kb/demo/controller/DocumentIngestionController.class]: Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'documentIngestionProducer' defined in URL [jar:nested:/D:/Project/enterprise-agent/target/ai-knowledge-base-0.0.1-SNAPSHOT.jar/!BOOT-INF/classes/!/com/kb/demo/mq/DocumentIngestionProducer.class]: Unsatisfied dependency expressed through constructor parameter 0: No qualifying bean of type 'org.apache.rocketmq.spring.core.RocketMQTemplate' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
2026-09-06T01:20:35.202+08:00  INFO 32892 --- [ai-knowledge-base] [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2026-09-06T01:20:35.203+08:00  INFO 32892 --- [ai-knowledge-base] [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2026-09-06T01:20:35.214+08:00  INFO 32892 --- [ai-knowledge-base] [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2026-09-06T01:20:35.217+08:00  INFO 32892 --- [ai-knowledge-base] [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2026-09-06T01:20:35.249+08:00  INFO 32892 --- [ai-knowledge-base] [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2026-09-06T01:20:35.329+08:00 ERROR 32892 --- [ai-knowledge-base] [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in com.kb.demo.mq.DocumentIngestionProducer required a bean of type 'org.apache.rocketmq.spring.core.RocketMQTemplate' that could not be found.


Action:

Consider defining a bean of type 'org.apache.rocketmq.spring.core.RocketMQTemplate' in your configuration.

