package com.kb.demo;

import io.github.cdimascio.dotenv.Dotenv;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableScheduling;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
/**
 * AI知识库应用启动类
 * 应用程序入口点
 * @author LiJingLin
 */
@SpringBootApplication
@EnableScheduling
public class AiKnowledgeBaseApplication {

	public static void main(String[] args) {
		// 加载.env文件中的环境变量（如果存在）
		try {
			Dotenv dotenv = Dotenv.configure().ignoreIfMissing().load();
			dotenv.entries().forEach(entry -> {
				System.setProperty(entry.getKey(), entry.getValue());
			});
		} catch (Exception e) {
			// Docker 环境下不需要 .env 文件，忽略错误
		}
		
		SpringApplication.run(AiKnowledgeBaseApplication.class, args);
	}

}
